version: "3.9"

services:

  backend:
    build: api
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./api:/usr/src/api
  db:
    build:
      context: ./api/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=appuser
      - POSTGRES_DB=lateshop
      - POSTGRES_PASSWORD=qaz123wsx
    ports:
      - 5432:5432
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
